# Generated by Django 4.2 on 2025-08-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file_type',
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
