# Generated by Django 4.2 on 2025-08-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='custom_message',
        ),
    ]
