# Generated by Django 4.2 on 2025-08-22 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_remove_room_members_room_user1_room_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('user1', 'user2')},
        ),
    ]
