# Generated by Django 4.2 on 2025-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_is_updated_alter_room_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
