# Generated by Django 4.2 on 2025-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_fileupload_message_fileupload_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='original_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to='chat_files/'),
        ),
    ]
