# Generated by Django 4.2 on 2025-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_fileupload_original_filename_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
