# Generated by Django 4.2 on 2025-09-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('chat', '0015_alter_room_unique_together_alter_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='groups.group'),
        ),
    ]
