# Generated by Django 4.2 on 2025-09-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channelmessage_file'),
        ('chat', '0016_fileupload_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='channel.channel'),
        ),
    ]
