# Generated by Django 4.2 on 2025-09-29 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_groupmessage_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0009_alter_channel_options_alter_channelmessage_options_and_more'),
        ('chat', '0017_fileupload_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_uploaded_files', to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to='chat_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_uploaded_files', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.room'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['user', 'uploaded_at'], name='file_upload_user_id_061c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['room', 'uploaded_at'], name='file_upload_room_id_c2621d_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['group', 'uploaded_at'], name='file_upload_group_i_dd6f85_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['channel', 'uploaded_at'], name='file_upload_channel_fa4779_idx'),
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='file_uploads',
        ),
    ]
