# Generated by Django 4.2 on 2025-09-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmember_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='members',
        ),
    ]
