# Generated by Django 4.2 on 2025-09-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_groupmember_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(default='text', max_length=10, null=True),
        ),
    ]
