# Generated by Django 4.2 on 2025-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
