# Generated by Django 4.2 on 2025-09-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_groupmessage_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
