# Generated by Django 4.2 on 2025-09-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_remove_groupmessage_is_read_groupmember_unread_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='unread_count',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
