# Generated by Django 4.2 on 2025-09-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_fileupload_channel'),
        ('channel', '0003_alter_channelmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_files', to='chat.fileupload'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message_type',
            field=models.CharField(blank=True, default='text', max_length=10, null=True),
        ),
    ]
