# Generated by Django 4.2 on 2025-09-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channelmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_message', to='channel.channel'),
        ),
    ]
