# Generated by Django 4.2 on 2025-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_channelmessage_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
