# Generated by Django 4.2 on 2025-09-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_channelmessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='is_updated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
