# Generated by Django 4.2 on 2025-09-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_channelmessage_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
