# Generated by Django 4.2 on 2025-09-29 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0017_fileupload_channel'),
        ('channel', '0008_channel_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='channelmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='channelmessage',
            old_name='context',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='channel_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_message_files', to='chat.fileupload'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='message_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='channel',
            table='channels',
        ),
        migrations.AlterModelTable(
            name='channelmessage',
            table='channel_messages',
        ),
    ]
